## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [3]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [4]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
dfbi = pd.read_csv("bridge-inspections-excerpt.csv")
dfbi

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [5]:
## call the first 10 rows
dfbi.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [6]:
## call the last 5 rows
dfbi.tail(5)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [7]:
## call a 20 random rows
dfbi.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
80389,51,69,'I-81 NBL',39003624.0,78175219.0,1.0,1.0,1964.0,3,2.0,5,5,5,N,N,NaN
4555,48,231,'DRAW',32585169.0,96172498.0,1.0,1.0,1957.0,1,19.0,N,N,N,7,6,NaN
44238,48,85,'WILSON CREEK',33154437.0,96450756.0,1.0,17.0,2003.0,5,2.0,7,8,7,7,N,NaN
52790,48,245,'MAIN A CANAL',29551501.0,93570838.0,1.0,12.0,1961.0,5,2.0,6,6,5,5,N,1.0
22812,48,455,'CANEY CREEK',31034240.0,95033723.0,1.0,7.0,1957.0,1,1.0,6,6,7,5,N,NaN
68223,48,139,'CHAMBERS DRIVE',32131356.0,96531637.0,NaN,9.0,2007.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
88217,51,199,'Mercury Blvd',37022672.0,76234307.0,1.0,11.0,2005.0,4,2.0,7,7,7,N,N,NaN
19334,48,309,'TRADING HOUSE CREEK',31371814.0,96524359.0,1.0,7.0,1993.0,1,2.0,7,7,8,7,N,NaN
21986,48,347,'LA NANA CREEK',31343768.0,94391732.0,1.0,14.0,1964.0,1,2.0,7,7,6,6,N,NaN
53230,48,291,'Community Drive Rd.',30075794.0,95031600.0,1.0,12.0,2021.0,5,2.0,8,8,8,N,N,NaN
38094,48,29,'SAN ANTONIO RIVER',29254725.0,98293437.0,4.0,19.0,1929.0,2,4.0,7,6,7,8,N,NaN
97693,53,63,'LINCOLN RD',47434440.0,117211900.0,1.0,12.0,2012.0,5,2.0,8,8,8,N,N,NaN
37607,48,29,'Leon Creek',29352566.0,98361353.0,1.0,12.0,1981.0,5,2.0,7,7,7,7,N,NaN
77953,51,19,'Battery Creek',37331461.0,79221148.0,1.0,6.0,1978.0,3,19.0,N,N,N,7,5,NaN
16388,48,417,'DRAW',32451079.0,99124629.0,1.0,6.0,1926.0,1,19.0,N,N,N,6,6,NaN
57619,48,141,'DRAIN',31565889.0,106345771.0,1.0,11.0,1959.0,2,1.0,7,7,7,7,N,NaN
94414,51,59,'I-66',38514866.0,77201136.0,NaN,NaN,2020.0,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN
45567,48,113,'IH 35E & DART Railway',32465488.0,96484642.0,1.0,12.0,1981.0,5,2.0,7,6,6,N,N,NaN
61828,48,451,'US 67',31274098.0,100273088.0,NaN,12.0,2002.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3330,48,119,'LAKE CREEK',33270792.0,95363475.0,1.0,7.0,1990.0,5,2.0,8,7,7,6,N,NaN

In [8]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

dfbi.info()
type(dfbi)
len(dfbi)

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

100000

### Which column has the most missing data...just a quick estimate?

In [9]:
## call the top 7 rows
dfbi.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [10]:
## call a sample of 10
dfbi.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
27236,48,201,'R.O.W.',29555339.0,95224302.0,2.0,6.0,1987.0,5,2.0,7,7,7,N,N,NaN
18064,48,145,'CEDAR CREEK #91',31201802.0,96474046.0,2.0,9.0,2013.0,1,19.0,N,N,N,7,7,NaN
65047,48,453,'ENFIELD RD',30170835.0,97454970.0,NaN,19.0,1971.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
84009,51,169,'COXS BRANCH',36375600.0,82544891.0,1.0,8.0,1962.0,1,19.0,N,N,N,5,7,NaN
61667,48,371,'IH 10',30534691.0,102582622.0,NaN,1.0,1971.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
34535,48,453,'WILBARGER CREEK BRANCH',30292431.0,97341628.0,2.0,9.0,2015.0,1,19.0,N,N,N,7,7,NaN
6154,48,251,'ROBINSON BRANCH',32193512.0,97302292.0,1.0,8.0,1957.0,1,19.0,N,N,N,7,6,NaN
2980,47,165,'SR109-RL/SUMNER HALL DR',36225538.0,86281357.0,NaN,19.0,1993.0,6,6.0,NaN,NaN,NaN,NaN,NaN,NaN
42338,48,41,'LICK CREEK',30342987.0,96173713.0,4.0,9.0,2001.0,1,19.0,N,N,N,7,7,NaN
13156,48,371,'DRAW',30462776.0,101571046.0,1.0,7.0,1932.0,1,19.0,N,N,N,7,7,NaN

In [11]:
## call the bottom 6
dfbi.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [12]:
## call the year built column using dot notation
dfbi.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [13]:
## call FEATURES_DESC_006A as a series using square bracket notation

dfbi["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [18]:
## what are the unique owner codes?
dfbi["OWNER_022"]

0        2.0
1        2.0
2        2.0
3        2.0
4        2.0
        ...
99995    2.0
99996    2.0
99997    2.0
99998    4.0
99999    2.0
Name: OWNER_022, Length: 100000, dtype: float64

In [ ]:
I recieved an error message when trying to run the cell for the unqiue owner code

In [21]:
dfbi["OWNER_022"].unqiue()

AttributeError: 'Series' object has no attribute 'unqiue'

### What do these codes mean?

In [ ]:
These codes mean which type of government, agency, or corporation owns the bridge